// Generated by gencpp from file msg_check/BoxMsg.msg
// DO NOT EDIT!


#ifndef MSG_CHECK_MESSAGE_BOXMSG_H
#define MSG_CHECK_MESSAGE_BOXMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace msg_check
{
template <class ContainerAllocator>
struct BoxMsg_
{
  typedef BoxMsg_<ContainerAllocator> Type;

  BoxMsg_()
    : header()
    , dimension()
    , mass(0.0)  {
    }
  BoxMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dimension(_alloc)
    , mass(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _dimension_type;
  _dimension_type dimension;

   typedef double _mass_type;
  _mass_type mass;





  typedef boost::shared_ptr< ::msg_check::BoxMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_check::BoxMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BoxMsg_

typedef ::msg_check::BoxMsg_<std::allocator<void> > BoxMsg;

typedef boost::shared_ptr< ::msg_check::BoxMsg > BoxMsgPtr;
typedef boost::shared_ptr< ::msg_check::BoxMsg const> BoxMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_check::BoxMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_check::BoxMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_check

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'msg_check': ['/home/rahul/catkin_ws/src/control/dependency/msg_check/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_check::BoxMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_check::BoxMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_check::BoxMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_check::BoxMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_check::BoxMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_check::BoxMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_check::BoxMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b50fa110ec2c02c572817edb20c0a4c9";
  }

  static const char* value(const ::msg_check::BoxMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb50fa110ec2c02c5ULL;
  static const uint64_t static_value2 = 0x72817edb20c0a4c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_check::BoxMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_check/BoxMsg";
  }

  static const char* value(const ::msg_check::BoxMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_check::BoxMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Vector3 dimension\n\
float64 mass\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::msg_check::BoxMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_check::BoxMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dimension);
      stream.next(m.mass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoxMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_check::BoxMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_check::BoxMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dimension: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.dimension);
    s << indent << "mass: ";
    Printer<double>::stream(s, indent + "  ", v.mass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_CHECK_MESSAGE_BOXMSG_H
